#!/bin/mksh
set -e

# Stew is a simple package manager for installing software outside of your
# distribution's repositories. It leverages the excellent GNU Stow utility to
# manage packages, but alleviates much of the boilerplate you might otherwise
# need to write if you wanted to automate your stow installations.

# configuration
prefix="$HOME/.local"
pkgpath="$HOME/src/stew/pkgs"

stowdir="$prefix/stow"

# A stew package is a shell script with the following properties:
#
#   * lives in a file named $name.pkg.sh in a directory in $pkgpath
#   * consists only of function and variable definitions (when run or sourced
#     it does nothing on its own)
#   * defines a `package` function which installs the software into $pkgdir
#     and runs stow on it 
#   * inherits the default implementation below

# This is the default implementation of the `package` function. You should not
# normally override this function. Instead, you should override the individual
# phases that it calls.
package() {
	. "$pkgpath/../stdenv.sh"
	download_phase
	setup_phase
	unpack_phase
	configure_phase
	build_phase
	install_phase
	cleanup_phase
	stow_phase
}

main() {
	if test -f "$pkgpath/$1.pkg.sh"; then
		(
			name="$1"
			pkgdir="$stowdir/$name"
			. "$pkgpath/$1.pkg.sh"

			# include $version in $pkgdir if it's defined
			if test "$version"; then
				pkgdir="$stowdir/$name-$version"
			fi

			# finally run the package function
			if ! test -d "$pkgdir"; then
				package
			fi
		)
	fi
}

main "$@"
