.Dd May 17, 2018
.Dt STEW 1
.Os
.Sh NAME
.Nm stew
.Nd manage software with GNU Stow
.Sh SYNOPSIS
.Nm
.Op Fl ilrs
.Op Ar pkg ...
.Sh DESCRIPTION
.Nm
is a simple source-based package manager for installing software
outside of your distribution's repositories,
leveraging the excellent
.Xr stow 8
utility.
It's not intended for distributing software to other users,
but for automating what would otherwise be manual installations.
.Pp
The operations are as follows:
.Bl -tag -width Ds
.It Fl i
Install the specified packages.
This is the default operation when a package name is specified.
.It Fl l
List installed packages.
This is the default operation when no packages are specified.
.It Fl r
Remove the specified packages.
If
.Nm
can't find the corresponding package definition in
.Ev $STEWPKGS ,
you may need to specify the version number as well.
.It Fl s
Search available packages.
The rest of the command line is used as a list of search terms
over package names and descriptions.
Packages must match all of the search terms.
If no arguments are given, display all available packages.
.El
.Pp
For documentation on creating your own packages, see
.Xr stew 5 .
.Sh INSTALLATION
To install
.Nm
into
.Ev $STEWPREFIX ,
run the following command from the source directory:
.Pp
.Dl $ make install
.Pp
Then make sure
.Pa $STEWPREFIX/bin
is in your
.Ev $PATH .
.Sh ENVIRONMENT
.Bl -tag -width MANPATHX
.It Ev STEWPKGS
Search for package definitions in this directory,
.Pq defaults to the current directory .
.It Ev STEWPREFIX
Install software under this directory
.Pq defaults to Pa ~/.local .
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Install the
.Li hello
package:
.Pp
.Dl $ stew hello
.Pp
Remove the
.Li hello
package:
.Pp
.Dl $ stew -r hello
.Pp
Upgrade the
.Li hello
package to a new version
.Pq an uninstall operation followed by an install :
.Pp
.Dl $ stew -r hello-2.9 -i hello
.Pp
List installed packages:
.Pp
.Dl $ stew
.Pp
List available packages:
.Pp
.Dl $ stew -s
.Pp
Search available packages matching both patterns
.Sq go
and
.Sq font :
.Pp
.Dl $ stew -s go font
.Sh SEE ALSO
.Xr stew 5 ,
.Xr stow 8
.Sh AUTHORS
Written by
.An Alex Griffin
.Aq Mt a@ajgrf.com ,
and licensed under the ISC license.
See the LICENSE file for details.
.Sh BUGS
Although stew's design should work fine under a variety of environments,
it may not yet be usable outside of Debian-based systems.
.Pp
No effort has been made to secure
.Nm .
You should not use it with untrusted input!
