#!/bin/mksh
set -e

# Stew is a simple package manager for installing software outside of your
# distribution's repositories. It leverages the excellent GNU Stow utility to
# manage packages, but alleviates much of the boilerplate you might otherwise
# need to write if you wanted to automate your stow installations.

# configuration
STEWPREFIX="${STEWPREFIX:-$HOME/.local}"
STEWPKGS="${STEWPKGS:-.}"

# A stew package is a shell script with the following properties:
#
#   * lives in a file named $name.pkg.sh in a directory in $STEWPKGS
#   * consists only of function and variable definitions (when run or sourced
#     it does nothing on its own)
#   * defines a `package` function which installs the software into $pkgdir
#     and runs stow on it 
#   * inherits a default implementation from stdenv.sh

usage() {
	cat <<-EOF 1>&2
		usage: stew <command> [<args>]

		The commands are:

		    add         install a package
		    list        list all installed stew packages
		    remove      uninstall a package

	EOF
	exit 2
}

main() {
	case "$1" in
		add|install)
			shift
			for pkg; do
				stew_install "$pkg"
			done
			;;
		list|ls|"")
			ls -1 "$STEWPREFIX/stow"
			;;
		remove|rm)
			shift
			for pkg; do
				stew_remove "$pkg"
			done
			;;
		*)
			if test -f "$STEWPKGS/$1.pkg.sh"; then
				main add "$@"
			else
				usage
			fi
			;;
	esac
}

stew_install() (
	if test -f "$STEWPKGS/$1.pkg.sh"; then
		name="$1"
		use stdenv
		. "$STEWPKGS/$1.pkg.sh"
		pkgdir="$STEWPREFIX/stow/$name${version:+-$version}"

		# finally run the package function
		if ! test -d "$pkgdir"; then
			package
		fi
	else
		error 3 "package $1 not found in $STEWPKGS"
	fi
)

stew_remove() (
	if test -d "$STEWPREFIX/stow/$1"; then
		pkgname="$1"
	elif test -f "$STEWPKGS/$1.pkg.sh"; then
		name="$1"
		use stdenv
		. "$STEWPKGS/$1.pkg.sh"
		pkgname="$name${version:+-$version}"
	fi

	if test "$pkgname"; then
		stow -d "$STEWPREFIX/stow" -D "$pkgname"
		rm -r "$STEWPREFIX/stow/$pkgname"
	else
		error 3 "could not find package $1 to remove"
	fi
)

# exit codes:
# 2 usage error
# 3 packaging error
error() {
	local code="$1"
	shift
	echo stew: "$@" >&2
	exit "$code"
}

use() {
	for dir in . "$STEWPREFIX/lib/stew"; do
		if test -f "$dir/$1.sh"; then
			. "$dir/$1.sh"
		fi
	done
}

main "$@"
